apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: keycloak-git-push-binding
  namespace: keycloak
spec:
  params:
    - name: git-url
      value: $(body.repository.clone_url)
    - name: git-revision
      value: $(body.after)
    - name: git-ref
      value: $(body.ref)
