apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: keycloak-build-trigger-template
  namespace: keycloak
spec:
  params:
    - name: git-url
      description: URL du depot Git
    - name: git-revision
      description: SHA du commit Git
      default: main
    - name: git-ref
      description: Reference Git (branche/tag)
      default: refs/heads/main
  resourcetemplates:
    - apiVersion: tekton.dev/v1
      kind: PipelineRun
      metadata:
        generateName: keycloak-build-deploy-
        namespace: keycloak
        labels:
          tekton.dev/pipeline: keycloak-build-deploy
          app.kubernetes.io/part-of: quebec
      spec:
        taskRunTemplate:
          serviceAccountName: pipeline
        pipelineRef:
          name: keycloak-build-deploy
        params:
          - name: GIT_URL
            value: $(tt.params.git-url)
          - name: GIT_REVISION
            value: $(tt.params.git-revision)
          - name: IMAGE_NAME
            value: image-registry.openshift-image-registry.svc:5000/keycloak/keycloak-custom
          - name: IMAGE_TAG
            value: latest
        workspaces:
          - name: source
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 2Gi
        timeouts:
          pipeline: 1h0m0s
