apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: keycloak

resources:
  - secrets-template.yaml
  - certificate.yaml
  - postgresql-statefulset.yaml
  - postgresql-service.yaml
  - keycloak.yaml
