parent=keycloak
import=common/keycloak

# Langue par défaut : français
locales=fr
defaultLocale=fr

# Feuilles de style : PatternFly hérité du parent + thème sombre du Quebec
styles=node_modules/@patternfly/patternfly/patternfly.min.css css/quebec.css

# Propriétés visuelles héritées et personnalisées
kcLogoLink=https://www.quebec.ca
kcLogoClass=login-pf-brand
